### ISSUE TITLE
Translation Support

### ISSUE THREAD

**Issue by JeysonFlores** [rbribeiro/wingpanel-indicator-dropbox#11]
Hey, will you add internationalization support to this? Or will you wait until you make a desktop app out of it?

**Comment by rbribeiro** [comment]
I am not sure, actually. I made this just for personal use, but it seems that it's been useful to other people too. The problem here is that indicators go against eOS team guidelines and there should be better ways to integrate cloud services to the system (like libcloudproviders). So, I think the best option would be to make a desktop app and use dock indicators like badges and progress bars
